#define HL_NAME(n) sdl_vk_##n
#include <hl.h>
#include <SDL3/SDL.h>
#include <SDL3/SDL_vulkan.h>

#define VK_NO_PROTOTYPES
#include <vulkan/vulkan.h>

/* Function pointers - short aliases for brevity in code */
#define vkGPDMP       vkGetPhysicalDeviceMemoryProperties
#define vkCI          vkCreateInstance
#define vkDI          vkDestroyInstance
#define vkEPD         vkEnumeratePhysicalDevices
#define vkGPDP        vkGetPhysicalDeviceProperties
#define vkGPDQFP      vkGetPhysicalDeviceQueueFamilyProperties
#define vkCD          vkCreateDevice
#define vkDD          vkDestroyDevice
#define vkGDQ         vkGetDeviceQueue
#define vkDSKHR       vkDestroySurfaceKHR
#define vkGPDSSKHR    vkGetPhysicalDeviceSurfaceSupportKHR
#define vkGPDSCKHR    vkGetPhysicalDeviceSurfaceCapabilitiesKHR
#define vkGPDSFKHR    vkGetPhysicalDeviceSurfaceFormatsKHR
#define vkGPDSPMKHR   vkGetPhysicalDeviceSurfacePresentModesKHR
#define vkCSKHR       vkCreateSwapchainKHR
#define vkDeSKHR      vkDestroySwapchainKHR
#define vkGSIKHR      vkGetSwapchainImagesKHR
#define vkANIKHR      vkAcquireNextImageKHR
#define vkQPKHR       vkQueuePresentKHR
#define vkCIV         vkCreateImageView
#define vkDIV         vkDestroyImageView
#define vkCRP         vkCreateRenderPass
#define vkDRP         vkDestroyRenderPass
#define vkCFB         vkCreateFramebuffer
#define vkDFB         vkDestroyFramebuffer
#define vkCSM         vkCreateShaderModule
#define vkDSM         vkDestroyShaderModule
#define vkCPL         vkCreatePipelineLayout
#define vkDPL         vkDestroyPipelineLayout
#define vkCGP         vkCreateGraphicsPipelines
#define vkDP          vkDestroyPipeline
#define vkCDSL        vkCreateDescriptorSetLayout
#define vkDDSL        vkDestroyDescriptorSetLayout
#define vkCDP         vkCreateDescriptorPool
#define vkDDP         vkDestroyDescriptorPool
#define vkADS         vkAllocateDescriptorSets
#define vkUDS         vkUpdateDescriptorSets
#define vkCCP         vkCreateCommandPool
#define vkDCP         vkDestroyCommandPool
#define vkACB         vkAllocateCommandBuffers
#define vkFCB         vkFreeCommandBuffers
#define vkBCB         vkBeginCommandBuffer
#define vkECB         vkEndCommandBuffer
#define vkRCB         vkResetCommandBuffer
#define vkQS          vkQueueSubmit
#define vkQWI         vkQueueWaitIdle
#define vkDWI         vkDeviceWaitIdle
#define vkCBuf        vkCreateBuffer
#define vkDBuf        vkDestroyBuffer
#define vkGBMR        vkGetBufferMemoryRequirements
#define vkAM          vkAllocateMemory
#define vkFM          vkFreeMemory
#define vkBBM         vkBindBufferMemory
#define vkMM          vkMapMemory
#define vkUM          vkUnmapMemory
#define vkCImg        vkCreateImage
#define vkDImg        vkDestroyImage
#define vkGIMR        vkGetImageMemoryRequirements
#define vkBIM         vkBindImageMemory
#define vkCSamp       vkCreateSampler
#define vkDSamp       vkDestroySampler
#define vkCS          vkCreateSemaphore
#define vkDS          vkDestroySemaphore
#define vkCF          vkCreateFence
#define vkDF          vkDestroyFence
#define vkWFF         vkWaitForFences
#define vkRF          vkResetFences
#define vkCmdBRP      vkCmdBeginRenderPass
#define vkCmdERP      vkCmdEndRenderPass
#define vkCmdBP       vkCmdBindPipeline
#define vkCmdBVB      vkCmdBindVertexBuffers
#define vkCmdBIB      vkCmdBindIndexBuffer
#define vkCmdBDS      vkCmdBindDescriptorSets
#define vkCmdDI       vkCmdDrawIndexed
#define vkCmdD        vkCmdDraw
#define vkCmdSV       vkCmdSetViewport
#define vkCmdSS       vkCmdSetScissor
#define vkCmdCA       vkCmdClearAttachments
#define vkCmdSDB      vkCmdSetDepthBias
#define vkCmdPB       vkCmdPipelineBarrier
#define vkCmdCBuf     vkCmdCopyBuffer
#define vkCmdCB2I     vkCmdCopyBufferToImage

/* The actual function pointer declarations - these match LDI/LDD macro names */
static PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr_global;

#define LDI(n) n = (PFN_##n)vkGIPA_inst(vkInstance, #n); if(!n) return false
#define LDD(n)  n = (PFN_##n)vkGIPA_dev(vkDevice, #n); if(!n) return false

static PFN_vkGetInstanceProcAddr vkGIPA_inst;
static PFN_vkGetDeviceProcAddr vkGIPA_dev;
static PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;
static PFN_vkCreateInstance vkCreateInstance;
static PFN_vkDestroyInstance vkDestroyInstance;
static PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;
static PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;
static PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;
static PFN_vkCreateDevice vkCreateDevice;
static PFN_vkDestroyDevice vkDestroyDevice;
static PFN_vkGetDeviceQueue vkGetDeviceQueue;
static PFN_vkDestroySurfaceKHR vkDestroySurfaceKHR;
static PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR;
static PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
static PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR;
static PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR;
static PFN_vkCreateSwapchainKHR vkCreateSwapchainKHR;
static PFN_vkDestroySwapchainKHR vkDestroySwapchainKHR;
static PFN_vkGetSwapchainImagesKHR vkGetSwapchainImagesKHR;
static PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR;
static PFN_vkQueuePresentKHR vkQueuePresentKHR;
static PFN_vkCreateImageView vkCreateImageView;
static PFN_vkDestroyImageView vkDestroyImageView;
static PFN_vkCreateRenderPass vkCreateRenderPass;
static PFN_vkDestroyRenderPass vkDestroyRenderPass;
static PFN_vkCreateFramebuffer vkCreateFramebuffer;
static PFN_vkDestroyFramebuffer vkDestroyFramebuffer;
static PFN_vkCreateShaderModule vkCreateShaderModule;
static PFN_vkDestroyShaderModule vkDestroyShaderModule;
static PFN_vkCreatePipelineLayout vkCreatePipelineLayout;
static PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;
static PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines;
static PFN_vkDestroyPipeline vkDestroyPipeline;
static PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;
static PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;
static PFN_vkCreateDescriptorPool vkCreateDescriptorPool;
static PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;
static PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;
static PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;
static PFN_vkCreateCommandPool vkCreateCommandPool;
static PFN_vkDestroyCommandPool vkDestroyCommandPool;
static PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;
static PFN_vkFreeCommandBuffers vkFreeCommandBuffers;
static PFN_vkBeginCommandBuffer vkBeginCommandBuffer;
static PFN_vkEndCommandBuffer vkEndCommandBuffer;
static PFN_vkResetCommandBuffer vkResetCommandBuffer;
static PFN_vkQueueSubmit vkQueueSubmit;
static PFN_vkQueueWaitIdle vkQueueWaitIdle;
static PFN_vkDeviceWaitIdle vkDeviceWaitIdle;
static PFN_vkCreateBuffer vkCreateBuffer;
static PFN_vkDestroyBuffer vkDestroyBuffer;
static PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;
static PFN_vkAllocateMemory vkAllocateMemory;
static PFN_vkFreeMemory vkFreeMemory;
static PFN_vkBindBufferMemory vkBindBufferMemory;
static PFN_vkMapMemory vkMapMemory;
static PFN_vkUnmapMemory vkUnmapMemory;
static PFN_vkCreateImage vkCreateImage;
static PFN_vkDestroyImage vkDestroyImage;
static PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;
static PFN_vkBindImageMemory vkBindImageMemory;
static PFN_vkCreateSampler vkCreateSampler;
static PFN_vkDestroySampler vkDestroySampler;
static PFN_vkCreateSemaphore vkCreateSemaphore;
static PFN_vkDestroySemaphore vkDestroySemaphore;
static PFN_vkCreateFence vkCreateFence;
static PFN_vkDestroyFence vkDestroyFence;
static PFN_vkWaitForFences vkWaitForFences;
static PFN_vkResetFences vkResetFences;
static PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass;
static PFN_vkCmdEndRenderPass vkCmdEndRenderPass;
static PFN_vkCmdBindPipeline vkCmdBindPipeline;
static PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers;
static PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer;
static PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;
static PFN_vkCmdDrawIndexed vkCmdDrawIndexed;
static PFN_vkCmdDraw vkCmdDraw;
static PFN_vkCmdSetViewport vkCmdSetViewport;
static PFN_vkCmdSetScissor vkCmdSetScissor;
static PFN_vkCmdClearAttachments vkCmdClearAttachments;
static PFN_vkCmdSetDepthBias vkCmdSetDepthBias;
static PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier;
static PFN_vkCmdCopyBuffer vkCmdCopyBuffer;
static PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage;
